import XCTest
@testable import Spire_Xls

class CreatePivotTableTests: TestCaseBase {
    func testCreatePivotTable() throws {
        try TestUtil.licenseKey()
        let outputFile = TestUtil.OutputPath + "Demo/CreatePivotTable.xlsx"

        let workbook = try Workbook()
        let sheet = try workbook.get_Worksheets().get_Item(0) as! Worksheet
        // Set the value to the cells
        try sheet.get_Range().get_Item("A1").set_Value("Product")
        try sheet.get_Range().get_Item("B1").set_Value("Month")
        try sheet.get_Range().get_Item("C1").set_Value("Count")

        try sheet.get_Range().get_Item("A2").set_Value("SpireDoc")
        try sheet.get_Range().get_Item("A3").set_Value("SpireDoc")
        try sheet.get_Range().get_Item("A4").set_Value("SpireXls")
        try sheet.get_Range().get_Item("A5").set_Value("SpireDoc")
        try sheet.get_Range().get_Item("A6").set_Value("SpireXls")
        try sheet.get_Range().get_Item("A7").set_Value("SpireXls")

        try sheet.get_Range().get_Item("B2").set_Value("January")
        try sheet.get_Range().get_Item("B3").set_Value("February")
        try sheet.get_Range().get_Item("B4").set_Value("January")
        try sheet.get_Range().get_Item("B5").set_Value("January")
        try sheet.get_Range().get_Item("B6").set_Value("February")
        try sheet.get_Range().get_Item("B7").set_Value("February")

        try sheet.get_Range().get_Item("C2").set_Value("10")
        try sheet.get_Range().get_Item("C3").set_Value("15")
        try sheet.get_Range().get_Item("C4").set_Value("9")
        try sheet.get_Range().get_Item("C5").set_Value("7")
        try sheet.get_Range().get_Item("C6").set_Value("8")
        try sheet.get_Range().get_Item("C7").set_Value("10")

        // Add a PivotTable to the worksheet
        let dataRange = try sheet.get_Range().get_Item("A1:C7") as! CellRange
        let cache = try workbook.get_PivotCaches().Add(dataRange)
        let pt = try sheet.get_PivotTables().Add("Pivot Table", try sheet.get_Range().get_Item("E10") as! CellRange, cache)

        // Drag the fields to the row area.
        let pf = try pt.get_PivotFields().get_Item("Product")
        try pf.set_Axis(AxisTypes.Row)
        let pf2 = try pt.get_PivotFields().get_Item("Month")
        try pf2.set_Axis(AxisTypes.Row)
        // Drag the field to the data area.
        try pt.get_DataFields().Add(try pt.get_PivotFields().get_Item("Count"), "SUM of Count", SubtotalTypes.Sum)
        // Set PivotTable style
        try pt.set_BuiltInStyle(PivotBuiltInStyles.PivotStyleMedium12)

        // Autofit columns generated by the pivotTable
        try pt.CalculateData()
        try sheet.AutoFitColumn(5)
        try sheet.AutoFitColumn(6)

        try workbook.SaveToFile(outputFile, ExcelVersion.Version2010)
        try workbook.Dispose()

        // Check data
        // let baseLineFile = TestUtil.BaseLinePath + "Demo/CreatePivotTable.xlsx"
        // Compare.compareFile(baseLineFile, outputFile)
    }
}

